Completed react-accordion-component exercise. - Charlie McCanna
cgmccanna/m3-0323-code-solutions pull request #15
Opened 2023-04-14 02:11 UTC by cgmccanna

![react-accordion-component](https://user-images.githubusercontent.com/74582871/231924002-107ac4b1-2da5-486c-a306-7ed450bacc3b.gif)

2023-04-14 02:14 UTC, dseong0224 commented on react-accordion-component/my-app/src/Accordion.js
> +      <Topic
try and use the map function to render the topics.

2023-04-14 02:15 UTC, dseong0224 requested changes
left a comment

2023-04-18 02:01 UTC, cgmccanna commented
![react-accordion-component2](https://user-images.githubusercontent.com/74582871/232650696-d144ca86-098e-4cad-955d-30c61bfb0547.gif)

2023-04-18 02:08 UTC, dseong0224 approved these changes

2023-04-20 05:54 UTC, merged