Completed react-state exercise. - Charlie McCanna
cgmccanna/m3-0323-code-solutions pull request #8
Opened 2023-03-28 04:10 UTC by cgmccanna

![react-state](https://user-images.githubusercontent.com/74582871/228123808-a8686898-f7e1-484a-bd61-d05fc951880b.gif)

2023-03-28 23:20 UTC, dseong0224 commented on react-state/my-app/src/ToggleButton.js
> +  const [isClicked, setClicked] = useState(false);
the setter should be named 'setIsClicked'. Not a big deal but just good practice to follow that convention.

2023-03-28 23:21 UTC, dseong0224 commented on react-state/my-app/src/ToggleButton.js
> +  if (isClicked) {
should we be checking for true or false value in this conditional?

2023-03-28 23:23 UTC, dseong0224 requested changes
just a couple things. almost there.

2023-03-29 00:46 UTC, cgmccanna commented
![react-state-2](https://user-images.githubusercontent.com/74582871/228398005-046b7b02-7514-4179-867a-ba65ad2083cc.gif)

2023-03-29 01:01 UTC, dseong0224 requested changes

2023-03-29 01:01 UTC, dseong0224 commented on react-state/my-app/src/ToggleButton.js
> +  if (isClicked) {
The code you had before was fine. 
#7 of the instructions want you to set the buttons to white by default. 
so the change should be made in the conditional.

2023-03-29 01:26 UTC, cgmccanna commented
![react-state-3](https://user-images.githubusercontent.com/74582871/228402633-3df886e3-3b14-434f-b974-a1c7c740548c.gif)

2023-03-29 01:27 UTC, dseong0224 approved these changes

2023-03-29 01:27 UTC, merged